Created directory models. Added user.js, post.js, data.js to models. …
Myuze/ubiquitous-happiness pull request #14
Opened 2021-09-29 16:29 UTC by mrogers23458

…Updated models with properties required in ticket.

2021-09-29 17:15 UTC, Myuze commented on moldels/data.js
> +module.exports = Data;
```suggestion
module.exports = Data;

```

2021-09-29 17:16 UTC, Myuze commented on moldels/index.js
> +  module.exports = { User, Post, Data };
```suggestion
  module.exports = { User, Post, Data };
  
```

2021-09-29 17:20 UTC, Myuze requested changes
Directory name should be models. Also, Capitalize the Model files as they are classes.

2021-09-29 17:26 UTC, mrogers23458 reviewed
pushed up new changes to use first letter capital on Models, and I updated spelling on moldels folder to models.

2021-09-30 02:51 UTC, LordLowdar reviewed
💩

2021-09-30 04:04 UTC, ENguyen25 approved these changes

2021-09-30 04:29 UTC, LordLowdar approved these changes

2021-09-30 04:30 UTC, LordLowdar approved these changes

2021-09-30 04:30 UTC, LordLowdar approved these changes

2021-09-30 04:31 UTC, LordLowdar approved these changes

2021-09-30 04:31 UTC, LordLowdar approved these changes
Sounds good

2021-09-30 04:32 UTC, LordLowdar approved these changes
💥

2021-09-30 04:32 UTC, LordLowdar approved these changes
💥

2021-09-30 04:40 UTC, merged