Temporarybranch
Myuze/ubiquitous-happiness pull request #66
Opened 2021-10-05 01:38 UTC by ENguyen25

2021-10-05 05:01 UTC, Myuze commented on .env.EXAMPLE
> -DB_PASSWORD=
You deleted the .env.EXAMPLE file again? ^^;

2021-10-05 05:05 UTC, Myuze commented on controllers/api/user-routes.js
> +  // if (user){
Should just remove this if it's not going to be used.

2021-10-05 05:08 UTC, Myuze commented on controllers/api/user-routes.js
> +      }
```suggestion
  const findUser = await User.findOne({
    where: {
        id: req.params.id,
        include: {
          model: 'User',
          attributes: [ 'id', 'username' ]
        }
    }
```

2021-10-05 05:21 UTC, Myuze commented on controllers/user-routes.js
>    });
It's better practice to check for the negative status first, also "else" already counts for the inverse of "user", so another "if" is not necessary.
`        if (!user) {
            res
            .status(200)
            .render('add-post', { message: 'Please login or register to make a new post.'})
        } else {
           res
            .status(200)
            .render('add-post') 
        }
    } catch (err) {
      console.log(err);
        res.status(500).json(err);
    }`

2021-10-05 05:52 UTC, Myuze commented on controllers/user-routes.js
> +    if (!user){
```suggestion
    } else {
```

2021-10-05 05:53 UTC, Myuze commented on controllers/user-routes.js
> +    if (!user){
I suggest checking for "if (!user)" first.

2021-10-05 05:54 UTC, Myuze commented on models/Comment.js
> +    modelName: 'comments',
```suggestion
    modelName: 'comment',
```

2021-10-05 06:03 UTC, Myuze commented on public/js/new-post.js
> +    .addEventListener('submit', newFormHandler);
```suggestion
    .addEventListener('submit', newFormHandler);
    
```

2021-10-05 06:13 UTC, Myuze commented on controllers/user-routes.js
> +})
I don't think this logic does what you think,
Line 73: If there is a "user session" please login?
Line 78: If there is a NOT a "user session" post an entry?
Seems backwards to me.

2021-10-05 06:14 UTC, Myuze commented on models/UserComment
> +module.exports = UserComment;
For the .js extension for the file.tt

2021-10-05 06:19 UTC, Myuze commented on models/index.js
> +})
The "through" property only works with belongsToMany releation ship in M:M or M:N.
[https://sequelize.org/master/manual/advanced-many-to-many.html](url)

2021-10-05 07:14 UTC, Myuze requested changes
Along with Michael's commits we need to discuss how the login flow works, and the proper way to validate before performing certain actions.

2021-10-06 17:51 UTC, Myuze commented on public/js/new-comment.js
> +
```suggestion
    .addEventListener('submit', newCommentHandler);

```

2021-10-06 17:52 UTC, Myuze commented on public/js/new-post.js
> +
```suggestion
    .addEventListener('submit', newFormHandler);

```

2021-10-07 05:22 UTC, LordLowdar approved these changes
༼ つ ◕_◕ ༽つ

2021-10-07 05:25 UTC, merged